- src/settings/components/CentralServersConfiguration/CentralServersConfigurationView/CentralServersConfigurationView.js
- src/settings/components/CentralServersConfiguration/CentralServersConfigurationView/CentralServersConfigurationView.test.js
- src/settings/components/CentralServersConfiguration/CentralServersConfigurationView/components/ActionItem/ActionItem.js
- src/settings/components/CentralServersConfiguration/CentralServersConfigurationView/components/ActionItem/ActionItem.test.js
- src/settings/components/CentralServersConfiguration/CentralServersConfigurationView/components/GeneralInformation/GeneralInformation.js
- src/settings/components/CentralServersConfiguration/CentralServersConfigurationView/components/GeneralInformation/GeneralInformation.test.js
- src/settings/components/CentralServersConfiguration/CentralServersConfigurationView/components/ServerConnection/ServerConnection.js
- src/settings/components/CentralServersConfiguration/CentralServersConfigurationView/components/ServerConnection/ServerConnection.test.js
- src/settings/components/common/EntityNotFound/EntityNotFound.test.js
- src/settings/components/common/FirsrMenuCloseButton/FirsrMenuCloseButton.js
- src/settings/components/common/FirsrMenuCloseButton/FirsrMenuCloseButton.test.js
- src/settings/index.js
- src/settings/routes/CentralServersConfigurationRoute/CentralServersConfigurationViewRoute.js
- test/jest/__mock__/index.js
- test/jest/__mock__/stripesSmartComponents.mock.js
[UIINREACH-26](https://issues.folio.org/browse/UIINREACH-26)
> UIINREACH-26: Add tests for UIINREACH-13

- src/settings/components/CentralServersConfiguration/CentralServersConfigurationForm/CentralServersConfigurationForm.js
- src/settings/components/CentralServersConfiguration/CentralServersConfigurationForm/CentralServersConfigurationForm.test.js
- src/settings/routes/CentralServersConfigurationRoute/CentralServersConfigurationCreateEditContainer.js
- src/settings/routes/CentralServersConfigurationRoute/CentralServersConfigurationCreateRoute.js
- src/settings/routes/CentralServersConfigurationRoute/CentralServersConfigurationCreateRoute.test.js
- src/settings/routes/CentralServersConfigurationRoute/CentralServersConfigurationEditRoute.js
- fixed screen size
- fixed incorrect appearance of the modal window
> UIINREACH-30: Invalid screen size for creating/editing central server configuration

- src/settings/index.js
- src/settings/index.test.js
- src/settings/routes/CentralServersConfigurationRoute/CentralServersConfigurationListRoute.js
- src/settings/routes/ContributionCriteriaRoute/ContributionCriteriaCreateEditRoute.js
Change the processing of central servers received from the BE
> UIINREACH-34: Change the processing of central servers received from the BE

- src/settings/routes/ContributionCriteriaRoute/ContributionCriteriaCreateEditRoute.js
Updated contribution criteria API according to  [UIINREACH-39](https://issues.folio.org/browse/UIINREACH-39)
> UIINREACH-39: Updated contribution criteria API

- src/constants/contribution-options.js
- src/settings/components/ContributionOptions/ContributionOptionsForm/ContributionOptionsForm.js
- src/settings/routes/ContributionOptionsRoute/ContributionOptionsCreateEditRoute.js
- src/settings/routes/ContributionOptionsRoute/ContributionOptionsCreateEditRoute.test.js
Integrated UI with backend API for item contribution options mapping
> UIINREACH-39: Integrated UI with backend API for item contribution options

- src/constants/base.js
- src/settings/routes/MaterialTypeRoute/MaterialTypeCreateEditRoute.js
- src/settings/routes/MaterialTypeRoute/utils.js
Fix save button disabling logic for material types mapping
> UIINREACH-45

- src/settings/routes/ContributionOptionsRoute/ContributionOptionsCreateEditRoute.js
Fixed circulation mapping record update according to [UIINREACH-54](https://issues.folio.org/browse/UIINREACH-54)
> UIINREACH-54: Fixed record update

- translations/ui-inn-reach/en.json
- translations/ui-inn-reach/en_US.json
> UIINREACH-49: Updated translation

- src/constants/central-item-type.js
- src/settings/components/CentralItemType/CentralItemTypeForm/CentralItemTypeForm.test.js
- src/settings/components/CentralItemType/CentralItemTypeForm/components/TabularList/TabularList.js
- src/settings/routes/CentralItemTypeRoute/CentralItemTypeCreateEditRoute.test.js
- src/settings/routes/CentralItemTypeRoute/utils.js
- change the constant name from itemType to centralItemType
> UIINREACH-67: Backend integration for 'Central item type'

- package.json
Update stripes v7 and reac t v17 according to https://issues.folio.org/browse/UIDEXP-246
> UIINREACH-66: Update strioes v7 and react to v17

- package.json
Downgraded stripes-data-transfer-components for pre-release
> Downgraded stripes-data-transfer-components for pre-release

- package.json
> UIINREACH-75: Change module version

- package.json
Reverts folio-org/ui-inn-reach#76
> Revert "UIINREACH-75: Change module version"

- src/settings/components/CentralItemType/CentralItemTypeForm/CentralItemTypeForm.js
- fixed titles in the 'central item type' table
> UIINREACH-95: Incorrect titles in the 'central item type' setting

- src/components/common/filters/FilterAccordion/FilterAccordion.js
- src/components/common/filters/MultiChoiceFilter/MultiChoiceFilter.js
- src/components/transaction/TransactionListFilters/TransactionListFilters.js
- src/components/transaction/TransactionListFilters/TransactionListFilters.test.js
- src/components/transaction/TransactionListFilters/utils.js
- src/constants/transactions.js
- translations/ui-inn-reach/en.json
> UIINREACH-62: INN-Reach Staff Interface: Filter INN-Reach Transactions by INN-Reach Patron Type

- package.json
Added recall user permissions according to https://issues.folio.org/browse/UIINREACH-117
> UIINREACH-117: Added recall user permissions

- src/components/transaction/TransactionList/transaction-list.js
- src/constants/transactions.js
- translations/ui-inn-reach/en.json
Integration with BE for transactions list
> UIINREACH-116: Transaction list BE integration

- src/constants/inn-reach-recall-user.js
- src/settings/components/InnReachRecallUser/InnReachRecallUserForm/InnReachRecallForm.js
- src/settings/components/InnReachRecallUser/InnReachRecallUserForm/InnReachRecallForm.test.js
- src/settings/routes/InnReachRecallUserRoute/InnReachRecallUserCreateEditRoute.js
- src/settings/routes/InnReachRecallUserRoute/InnReachRecallUserCreateEditRoute.test.js
- changed name of the field
- removed the automatic creation of an id for a request
> UIINREACH-125: BE integration for 'INN-Reach Recall User' setting

- src/components/ReceiveShippedItem/ReceiveShippedItem.js
- change Modal content on 'Receive Shipped Item' page"
> UIINREACH-137: INN-Reach Staff Interface: change Modal content on 'Receive Shipped Item' page"

- src/components/ReceiveShippedItem/ReceiveShippedItem.js
- src/components/ReceiveShippedItem/ReceiveShippedItem.test.js
- src/components/ReceiveShippedItem/components/CheckIn/components/ListCheckInItems/ListCheckInItems.test.js
- src/components/ReceiveShippedItem/components/CheckIn/components/ListCheckInItems/components/ItemActions/ItemActions.js
- src/components/ReceiveShippedItem/components/CheckIn/components/ListCheckInItems/components/ItemActions/ItemActions.test.js
- removed unnecessary printing logic
> UIINREACH-139: INN-Reach Staff Interface: Receive Shipped Item - remove unnecessary print logic

- package.json
- updated the @folio/stripes-cli version
> UIINREACH-140: Update the @folio/stripes-cli version

- src/components/ReceiveShippedItem/ReceiveShippedItem.js
- src/components/ReceiveShippedItem/components/CheckIn/components/ListCheckInItems/components/ItemActions/ItemActions.js
- src/components/ReceiveShippedItem/components/ConfirmStatusModal/ConfirmStatusModal.js
- translations/ui-inn-reach/en.json
- change the display of modal windows
> UIINREACH-145: INN-Reach Staff Interface: Receive Shipped Item - modal window behavior

- src/components/common/SearchAndFilter/SearchAndFilter.js
- src/components/common/SearchAndFilter/SearchAndFilter.test.js
- src/components/transaction/TransactionList/transaction-list.js
- src/constants/base.js
- src/constants/index.js
- src/constants/owning-site-overdue.js
- src/constants/requested-too-long.js
- src/constants/transactions.js
- src/routes/transaction/TransactionListRoute.js
- src/routes/transaction/TransactionListRoute.test.js
- src/routes/transaction/utils.js
- src/utils/routing.js
- translations/ui-inn-reach/en.json
Download a CSV file of INN-Reach Patron Hold transactions where requested item has not been filled by the owning site.
https://issues.folio.org/browse/UIINREACH-134
> UIINREACH-134: INN-Reach In-app Report: Borrowing Site Stale Requests Report (Requested too Long)

- src/settings/routes/ManageContributionRoute/ManageContribution.js
- src/settings/routes/ManageContributionRoute/ManageContribution.test.js
Manage contribution (cancellation)
https://issues.folio.org/browse/UIINREACH-96
> UIINREACH-96: Manage contribution (cancellation): BE integration

- src/components/CheckOutBorrowingSite/components/ListCheckOutItems/components/ItemActions/ItemActions.js
- src/components/CheckOutBorrowingSite/components/ListCheckOutItems/components/ItemActions/ItemActions.test.js
- src/components/ReceiveShippedItem/components/CheckIn/components/ListCheckInItems/components/ItemActions/ItemActions.js
- src/components/ReceiveShippedItem/components/CheckIn/components/ListCheckInItems/components/ItemActions/ItemActions.test.js
- src/components/transaction/TransactionDetails/TransactionDetail.js
- src/components/transaction/TransactionDetails/TransactionDetail.test.js
- src/components/transaction/TransactionDetails/TransactionDetailContainer.js
- src/components/transaction/TransactionDetails/TransactionDetailContainer.test.js
- src/components/transaction/TransactionDetails/components/ActionMenu/ActionMenu.js
- src/components/transaction/TransactionDetails/components/ActionMenu/ActionMenu.test.js
- src/components/transaction/TransactionDetails/components/ActionMenu/components/PatronActions/PatronActions.js
- src/components/transaction/TransactionDetails/components/ActionMenu/components/PatronActions/PatronActions.test.js
- translations/ui-inn-reach/en.json
Cancel the transaction.
https://issues.folio.org/browse/UIINREACH-81
> UIINREACH-81: INN-Reach Staff Interface: INN-Reach Transaction Detail View Action Menu (Patron hold) - Cancel hold

- src/components/transaction/TransactionDetails/TransactionDetail.js
- src/components/transaction/TransactionDetails/TransactionDetail.test.js
- src/components/transaction/TransactionDetails/TransactionDetailContainer.js
- src/components/transaction/TransactionDetails/TransactionDetailContainer.test.js
- src/components/transaction/TransactionDetails/components/ActionMenu/ActionMenu.js
- src/components/transaction/TransactionDetails/components/ActionMenu/components/ItemActions/ItemActions.js
- translations/ui-inn-reach/en.json
Added cancel item hold action 
[UIINREACH-88](https://issues.folio.org/browse/UIINREACH-88)
> UIINREACH-88: Cancel item hold

- src/components/transaction/TransactionDetails/TransactionDetail.js
- src/components/transaction/TransactionDetails/TransactionDetail.test.js
- src/components/transaction/TransactionDetails/TransactionDetailContainer.js
- src/components/transaction/TransactionDetails/TransactionDetailContainer.test.js
- src/components/transaction/TransactionDetails/components/ActionMenu/ActionMenu.js
- src/components/transaction/TransactionDetails/components/ActionMenu/ActionMenu.test.js
- src/components/transaction/TransactionDetails/components/ActionMenu/components/ItemActions/ItemActions.js
- src/components/transaction/TransactionDetails/components/ActionMenu/components/ItemActions/ItemActions.test.js
- src/components/transaction/TransactionDetails/components/ActionMenu/components/LocalActions/LocalActions.js
- src/components/transaction/TransactionDetails/components/ActionMenu/components/LocalActions/LocalActions.test.js
- translations/ui-inn-reach/en.json
Added Cancel local hold action
[UIINREACH-93](https://issues.folio.org/browse/UIINREACH-93)
> UIINREACH-93: Cancel local hold action

- src/components/transaction/TransactionDetails/components/ActionMenu/components/ItemActions/ItemActions.js
> UIINREACH-89: Added ITEM_IN_TRANSIT state

- src/settings/components/ManageContribution/ManageContributionView.js
- src/settings/components/ManageContribution/components/CurrentContribution/CurrentContribution.js
- src/settings/components/ManageContribution/components/Footer/Footer.js
- src/settings/components/ManageContribution/components/Footer/Footer.test.js
- src/settings/routes/ManageContributionRoute/ManageContribution.js
- translations/ui-inn-reach/en.json
1) Added tooltip to the Initiate contribution button id the configuration is not valid
2) Added loading indication when the contribution in progress
3) Added Refresh button for the contribution statistics
> UIINREACH-55: Manage contribution updates

- .gitignore
- CHANGELOG.md
- src/settings/components/FolioCirculationUser/FolioCirculationUserForm/components/TabularList/utils.js
- src/settings/routes/CentralPatronTypeRoute/CentralPatronTypeCreateEditRoute.js
- src/settings/routes/CentralPatronTypeRoute/CentralPatronTypeCreateEditRoute.test.js
- src/settings/routes/CentralPatronTypeRoute/utils.js
purpose:
https://issues.folio.org/browse/UIINREACH-194
https://issues.folio.org/browse/UIINREACH-195
approach:
limit param for users and patron mapping requests
> UIINREACH-195, UIINREACH-194 fix issues with 10 limit

- CHANGELOG.md
- package.json
update package json and changelog to reflect patch release v2.0.1 metadata
> UIINREACH-198 - ui-inn-reach: release

- CHANGELOG.md
- package.json
- src/components/CheckOutBorrowingSite/components/ListCheckOutItems/ListCheckOutItems.js
- src/components/transaction/TransactionDetails/components/PatronInformation/PatronInformation.js
- src/components/transaction/TransactionDetails/components/PatronInformation/PatronInformation.test.js
- src/constants/checkout-shipped-items.js
- src/routes/transaction/utils.js
- src/settings/routes/VisiblePatronIdRoute/VisiblePatronIdCreateEditRoute.js
ui-innreach 2.0.2 patch release
Issue: https://issues.folio.org/browse/UIINREACH-211
The below tickets are cherry picked in the same order to include in the long live branch -
UIINREACH-188
UIINREACH-200 - (commit message goes like: Transaction.....)
UIINREACH-192
UIINREACH-201
UIINREACH-202
UIINREACH-199
UIINREACH-205 - (commit message goes like: update params....)
> UI-INREACH-211-patch

- CHANGELOG.md
- src/settings/routes/FolioToInnReachLocations/FolioToInnReachLocationsCreateEditRoute.js
INN-Reach: FOLIO to INN-Reach locations mapping configuration not displaying properly
Issue: https://issues.folio.org/browse/UIINREACH-208
> update limit param for locations and libraries API GET calls

- CHANGELOG.md
- src/settings/routes/AgencyToFolioLocations/utils.js
INN-Reach: Agency to FOLIO location map configuration not displaying correctly
Issue: https://issues.folio.org/browse/UIINREACH-209
Before:
After:
> UIINREACH-209 - INN-Reach: Agency to FOLIO location map configuration not displaying correctly

- CHANGELOG.md
- package.json
Release UIINREACH Morning Glory
Issue: https://issues.folio.org/browse/UIINREACH-212
> UIINREACH-212 - Release UIINREACH Morning Glory

- CHANGELOG.md
- package.json
- src/components/common/SearchAndFilter/components/PrintSlips/PrintSlips.js
- test/jest/helpers/translationsProperties.js
Bump stripes to 8.0.0 for Orchid/2023-R1
https://issues.folio.org/browse/UIINREACH-215
> UIINREACH-215 - bump stripes to 8.0.0 for Orchid/2023-R1

- CHANGELOG.md
- src/settings/components/CentralServersConfiguration/CentralServersConfigurationForm/CentralServersConfigurationForm.test.js
Fix test failures caused due to changes in STCOM-1079
https://issues.folio.org/browse/UIINREACH-217
> UIINREACH-217 - Fix test failures caused due to changes in STCOM-1079

- CHANGELOG.md
- src/components/common/PrintButton/PrintButton.css
- src/components/common/SearchAndFilter/components/PrintSlips/PrintSlips.js
- src/components/common/SearchAndFilter/components/PrintSlips/PrintSlips.test.js
INN-Reach paging slips not breaking pages between slips
https://issues.folio.org/browse/UIINREACH-219
> UIINREACH-219 - INN-Reach paging slips not breaking pages between slips

- .github/workflows/build-npm-release.yml
- .github/workflows/build-npm.yml
- CHANGELOG.md
- PULL_REQUEST_TEMPLATE.md
- package.json
- test/jest/babel.config.js
Add PULL_REQUEST_TEMPLATE.md file to the repository.
Update Node.js to v18 in GitHub Actions
Upgrade babel config
Currently unit tests fail.
It is needed to update dependencies associated with babel options config.
Leverage stripes-cli babel options for babel options to address this.
https://issues.folio.org/browse/UIINREACH-225
https://issues.folio.org/browse/UIINREACH-228
https://issues.folio.org/browse/UIINREACH-229
> UIINREACH-228, UIINREACH-225 - Add pull request template, update node js version to 18 for CI

- CHANGELOG.md
- package.json
- src/settings/routes/PatronAgency/PatronAgencyCreateEditRoute.test.js
[UIINREACH](https://issues.folio.org/browse/UIINREACH-227) - upgrade React to v18
Before merging this PR, please go through the following list and take appropriate actions.
- Does this PR meet or exceed the expected quality standards?
- Does this introduce breaking changes?
If there are breaking changes, please **STOP** and consider the following:
- What other modules will these changes impact?
- Do JIRAs exist to update the impacted modules?
- Are the JIRAs under active development?
- Do PRs exist for these changes?
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.
While it's …
> UIINREACH-227 - Upgrade React to v18

- CHANGELOG.md
- package.json
- test/jest/__mock__/index.js
- test/jest/__mock__/resizeObserver.mock.js
https://folio-org.atlassian.net/browse/UIINREACH-232
In this release, few translations were updated and no development happened. 
Test cases are failing here because of some update in dependencies or 3rd part libraries. Hence the tests are being fixed in this release task.
Before merging this PR, please go through the following list and take appropriate actions.
- Does this PR meet or exceed the expected quality standards?
- Does this introduce breaking changes?
If there are breaking changes, please **STOP** and consider the following:
- What other modules will these changes impact?
- Do JIRAs exist to update the impacted modules?
- Are the JIRAs under active development?
- Do PRs exist for these changes?
Ideally all of the PRs involved in breaking changes would be merged in the same day …
> Release v4.1.0 - Quesnelia

- CHANGELOG.md
- package.json
https://folio-org.atlassian.net/browse/UIINREACH-250; https://folio-org.atlassian.net/browse/UIINREACH-251
> UIINREACH-250, UIINREACH-251: migrate stripes-* deps; react-intl to v7
