- src/constants/base.js
- src/settings/routes/ContributionCriteriaRoute/ContributionCriteriaCreateEditRoute.js
- src/settings/routes/ContributionCriteriaRoute/ContributionCriteriaCreateEditRoute.test.js
- src/settings/routes/FolioToInnReachLocations/FolioToInnReachLocationsCreateEditRoute.js
- src/settings/routes/FolioToInnReachLocations/FolioToInnReachLocationsCreateEditRoute.test.js
- removed metadata
- made the Save button disabled after a successful request
- updated field values when changing the central server
- removed unexpecting LoadingPane component loading
- changed paths for library and location mappings
> UIINREACH-36: Configure FOLIO Libraries and Shelving Locations to INN-Reach Locations Mapping - create/edit backend integration

- src/hooks/useCentralServers/useCentralServers.js
- src/hooks/useCentralServers/useCentralServers.test.js
- src/settings/components/CentralServersConfiguration/CentralServersConfigurationForm/CentralServersConfigurationForm.js
- src/settings/components/CentralServersConfiguration/CentralServersConfigurationForm/CentralServersConfigurationForm.test.js
- src/settings/routes/CentralServersConfigurationRoute/CentralServersConfigurationCreateEditContainer.js
- src/settings/routes/CentralServersConfigurationRoute/CentralServersConfigurationCreateEditContainer.test.js
- src/settings/routes/CentralServersConfigurationRoute/CentralServersConfigurationCreateRoute.js
- src/settings/routes/CentralServersConfigurationRoute/CentralServersConfigurationCreateRoute.test.js
- src/settings/routes/CentralServersConfigurationRoute/CentralServersConfigurationEditRoute.js
- src/settings/routes/CentralServersConfigurationRoute/CentralServersConfigurationEditRoute.test.js
- removed the opening of a modal window when the central server is changed with dirty data
- fixed incorrect detection of central server data change in getIsCentralServerDataChanged function
- made a general modal window for creating and editing functionality
> UIINREACH-37: The modal does not show up, when leaving the page

- src/constants/agency-to-folio-locations.js
- src/hooks/useCentralServers/useCentralServers.js
- src/settings/components/AgencyToFolioLocations/AgencyToFolioLocationsForm/AgencyToFolioLocationsForm.js
- src/settings/components/AgencyToFolioLocations/AgencyToFolioLocationsForm/AgencyToFolioLocationsForm.test.js
- src/settings/components/AgencyToFolioLocations/AgencyToFolioLocationsForm/components/TabularList/TabularList.js
- src/settings/components/AgencyToFolioLocations/AgencyToFolioLocationsForm/utils.js
- src/settings/components/ContributionOptions/ContributionOptionsForm/ContributionOptionsForm.test.js
- src/settings/components/MaterialType/MaterialTypeForm/MaterialTypeForm.test.js
- src/settings/routes/AgencyToFolioLocations/AgencyToFolioLocationsCreateEditRoute.js
- src/settings/routes/AgencyToFolioLocations/AgencyToFolioLocationsCreateEditRoute.test.js
- src/settings/routes/AgencyToFolioLocations/utils.js
- src/settings/routes/ContributionOptionsRoute/ContributionOptionsCreateEditRoute.test.js
- fixed behavior after selecting the default option
- removed displaying of an empty value in the 'values' prop
- deleted error callout for local servers
- removed test errors
> UIINREACH-48: Agency to FOLIO location - incorrect behavior after selecting the local server field placeholder

- CHANGELOG.md
- package.json
Earlier versions of `uuid` cause a build warning.
Attn: @Dmytro-Melnyshyn, @Godlevskyi 
Refs [UIINREACH-127](https://issues.folio.org/browse/UIINREACH-127)
> UIINREACH-127 use supported uuid

- src/components/ReceiveShippedItem/ReceiveShippedItem.js
- src/components/ReceiveShippedItem/components/CheckIn/components/ListCheckInItems/components/ItemActions/ItemActions.js
- added display of the `hold`/`transit` modal window after clicking the `Close` button in the `item augmented` modal window
- the `Print barcode slip` checkbox is unchecked by default for non-augmented items
> UIINREACH-145: Receive Shipped Item - modal window behavior

- src/components/common/filters/MultiChoiceFilter/MultiChoiceFilter.test.js
- src/components/transaction/TransactionDetails/TransactionDetail.js
- src/components/transaction/TransactionDetails/TransactionDetail.test.js
- src/components/transaction/TransactionDetails/TransactionDetailContainer.js
- src/components/transaction/TransactionDetails/TransactionDetailContainer.test.js
- src/components/transaction/TransactionDetails/components/ActionMenu/ActionMenu.js
- src/components/transaction/TransactionDetails/components/ActionMenu/ActionMenu.test.js
- src/components/transaction/TransactionDetails/components/ActionMenu/components/PatronActions/PatronActions.js
- src/hooks/useList.js
- src/hooks/useList.test.js
- src/index.js
- src/index.test.js
- src/routes/transaction/TransactionListRoute.js
- src/routes/transaction/TransactionListRoute.test.js
- src/settings/components/CentralServersConfiguration/CentralServersConfigurationForm/CentralServersConfigurationForm.test.js
- src/settings/components/CentralServersConfiguration/CentralServersConfigurationForm/components/TabularList/TabularList.test.js
- src/settings/components/ContributionCriteria/ContributionCriteriaForm/ContributionCriteriaForm.test.js
- src/settings/components/ContributionOptions/ContributionOptionsForm/ContributionOptionsForm.test.js
- translations/ui-inn-reach/en.json
- add functionality for receiving the shipped item in the action menu of the transaction detail view
- update the list of transactions if the action of the detail view menu has changed the transaction and the changed value of the transaction is displayed in the list
- fixed test warnings
https://issues.folio.org/browse/UIINREACH-79
> UIINREACH-79: INN-Reach Staff Interface: INN-Reach Transaction Detail View Action Menu (Patron hold) - Receive item

- src/components/ReceiveShippedItem/ReceiveShippedItem.js
- src/components/ReceiveShippedItem/components/CheckIn/components/ListCheckInItems/components/ItemActions/ItemActions.js
- src/components/ReceiveShippedItem/components/CheckIn/components/ListCheckInItems/components/ItemActions/ItemActions.test.js
- src/components/ReceiveShippedItem/components/ConfirmStatusModal/ConfirmStatusModal.js
- translations/ui-inn-reach/en.json
- to display two action buttons (`Print INN-Reach barcode` and `Print transit slip`) in the action menu `...` for the `augmented barcode` with the `In transit` status and two buttons (`Print INN-Reach barcode` and `Print hold slip`) for the `augmented barcode` with the `Awaiting pickup` status
- dismissing the first modal before the second is presented
[UIINREACH-109 PO comment](https://issues.folio.org/browse/UIINREACH-109?focusedCommentId=122091&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-122091)
> UIINREACH-145: INN-Reach Staff Interface: Receive Shipped Item - modal window behavior

- src/constants/central-server-configuration.js
- src/constants/folio-to-innreach-locations.js
- src/settings/components/CentralServersConfiguration/CentralServersConfigurationView/components/GeneralInformation/GeneralInformation.js
- src/settings/components/FolioToInnReachLocations/FolioToInnReachLocationsForm/FolioToInnReachLocationsForm.css
- src/settings/components/FolioToInnReachLocations/FolioToInnReachLocationsForm/FolioToInnReachLocationsForm.js
- src/settings/components/FolioToInnReachLocations/FolioToInnReachLocationsForm/FolioToInnReachLocationsForm.test.js
- src/settings/components/FolioToInnReachLocations/FolioToInnReachLocationsForm/utils.js
- src/settings/components/common/TableStyleList/TableStyleList.js
- src/settings/routes/CentralServersConfigurationRoute/CentralServersConfigurationEditRoute.test.js
- src/settings/routes/CentralServersConfigurationRoute/utils.js
- src/settings/routes/FolioToInnReachLocations/FolioToInnReachLocationsCreateEditRoute.js
- src/settings/routes/FolioToInnReachLocations/FolioToInnReachLocationsCreateEditRoute.test.js
- src/settings/routes/FolioToInnReachLocations/utils.js
- translations/ui-inn-reach/en.json
Update the FOLIO to INN-Reach locations settings screen to group libraries by agency code AND prevent INN-Reach locations from being assigned to libraries or locations in more than one agency.
[UIINREACH-100](https://issues.folio.org/browse/UIINREACH-100)
> UIINREACH-100: FOLIO to INN-Reach Locations Settings Should Group Mappings by INN-Reach Agency

- src/components/common/HoldModal/HoldModal.js
- src/components/common/InTransitModal/InTransitModal.js
- src/components/transaction/TransactionDetails/TransactionDetailContainer.js
- src/components/transaction/TransactionDetails/TransactionDetailContainer.test.js
- src/components/transaction/TransactionDetails/components/ActionMenu/ActionMenu.test.js
- src/hooks/useList.js
- src/hooks/useList.test.js
Show the `The barcode for this item already exists in FOLIO` and `In transit` or `Awaiting pickup` modals, when the barcode is augmented.
useList hook: when scrolling fast, transaction requests can be executed with the same offset. Hence the transactions with repetitions.
[UIINREACH-147](https://issues.folio.org/browse/UIINREACH-147)
> UIINREACH-147: INN-Reach Staff Interface: Receive Shipped Item Action: Barcode Augmented Message

- src/settings/components/BibTransformationOptions/BibTransformationOptionsForm/BibTransformationOptionsForm.js
- src/settings/components/BibTransformationOptions/BibTransformationOptionsForm/BibTransformationOptionsForm.test.js
- src/settings/routes/BibTransformationOptions/BibTransformationOptionsCreateEditRoute.js
- src/settings/routes/BibTransformationOptions/BibTransformationOptionsCreateEditRoute.test.js
Fix not being to specify strip fields and subfields unless "Modify MARC 001 field for contributed records" is selected.
[UIINREACH-138](https://issues.folio.org/browse/UIINREACH-138)
> UIINREACH-138: Unable to specify strip fields and subfields if 'Modify MARC 001 field for contributed records' is not selected

- src/settings/routes/AgencyToFolioLocations/index.js
- src/settings/routes/BibTransformationOptions/index.js
- src/settings/routes/CentralItemTypeRoute/index.js
- src/settings/routes/CentralPatronTypeRoute/index.js
- src/settings/routes/CentralServersConfigurationRoute/index.js
- src/settings/routes/ContributionCriteriaRoute/index.js
- src/settings/routes/ContributionOptionsRoute/index.js
- src/settings/routes/FolioCirculationUserRoute/index.js
- src/settings/routes/FolioToInnReachLocations/index.js
- src/settings/routes/InnReachRecallUserRoute/index.js
- src/settings/routes/ManageContributionRoute/index.js
- src/settings/routes/MaterialTypeRoute/index.js
- src/settings/routes/PatronAgency/index.js
- src/settings/routes/VisiblePatronIdRoute/index.js
react-hot-loader should be replaced because it is no longer maintained and has security issues.
> UIINREACH-160: Replace react-hot-loader - unmaintained, security (CVE-2021-44906)

- src/components/CheckOutBorrowingSite/components/ListCheckOutItems/ListCheckOutItems.js
- src/components/CheckOutBorrowingSite/components/ListCheckOutItems/ListCheckOutItems.test.js
- src/components/ReceiveShippedItem/components/CheckIn/components/ListCheckInItems/ListCheckInItems.js
Fix the display of the `due date` and `time` column values.
[UIINREACH-171](https://issues.folio.org/browse/UIINREACH-171)
> UIINREACH-171: Check out to borrowing sites result list loan due date information displays the loan date, not the due date

- CHANGELOG.md
- src/components/CheckOutBorrowingSite/components/ListCheckOutItems/ListCheckOutItems.js
- src/constants/checkout-shipped-items.js
Issue: [UIINREACH-188](https://issues.folio.org/browse/UIINREACH-188)
Short description or steps to reproduce 
1. While in 'INN-Reach' application, select "Check out to borrowing site" from select menu on left pane, beneath 'Select activity'
2. Check out an item(associated with ui-inn-reach transaction, in ITEM_HOLD status) in right pane.
3. There will be a table displayed beneath the scsn items form, from the last column 'Actions', select 'Change due data'.
4. Change time in the modal that opens up and click save and close.
5. The time updates on the modal too.
6. Close the modal.
7. The issue is that the new value of time should be displayed on the table in column 'Time'.
Before
After
> UIINREACH-188 - The time change is not displayed in the table on the “Check out to borrowing site” screen.

- src/components/common/filters/MultiChoiceFilter/MultiChoiceFilter.js
- src/components/transaction/TransactionDetails/components/TransactionSummary/TransactionSummary.js
- src/settings/components/CentralServersConfiguration/CentralServersConfigurationView/components/GeneralInformation/GeneralInformation.js
`stripes-smart-components` modules should be imported as `@folio/stripes/smart-components`
Otherwise it gives errors during Jenkins build:
> Fix import path for @folio/stripes/smart-components

- CHANGELOG.md
- package.json
query-string is incorrectly listed as a peer-dependency
Issue: https://issues.folio.org/browse/UIINREACH-202
> UIINREACH-202 - remove 'query-string' from dependencies

- CHANGELOG.md
- src/settings/routes/VisiblePatronIdRoute/VisiblePatronIdCreateEditRoute.js
Visible patron ID configuration always includes "User custom fields" selected
Issue: UIINREACH-199
> UIINREACH-199 - Visible patron ID configuration always includes "User custom fields" selected

- CHANGELOG.md
- package.json
- Refs https://issues.folio.org/browse/UIINREACH-216 .
- Upgrade will be happening across all of Stripes framework and modules that reference react-redux.
- v7 to v8 is a very harmless upgrade and is only considered breaking since they removed a few rarely used functions (which I confirmed we don't use). See https://github.com/reduxjs/react-redux/releases/tag/v8.0.0 for more details.
> UIINREACH-216 Upgrade react-redux to v8.

- CHANGELOG.md
- src/settings/components/PagingSlipTemplate/PagingSlipTemplateForm/getTokens.js
Remove innReachTransaction.pickupLocationPrintName token from staff slips.
https://issues.folio.org/browse/UIINREACH-222
> UIINREACH-222 - Remove innReachTransaction.pickupLocationPrintName token from staff slips.

- CHANGELOG.md
- src/settings/components/AgencyToFolioLocations/AgencyToFolioLocationsForm/AgencyToFolioLocationsForm.css
[UIINREACH-233](https://folio-org.atlassian.net/browse/UIINREACH-233) - Refactor away from postcss-color-function.
Before merging this PR, please go through the following list and take appropriate actions.
- Does this PR meet or exceed the expected quality standards?
- Does this introduce breaking changes?
If there are breaking changes, please **STOP** and consider the following:
- What other modules will these changes impact?
- Do JIRAs exist to update the impacted modules?
- Are the JIRAs under active development?
- Do PRs exist for these changes?
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team …
> UIINREACH-233 - Refactor away postcss-color-function

- CHANGELOG.md
- src/routes/transaction/utils.js
Adjust URL params for the corresponding API call: include `createdDate` param with the appropriate date as selected by the user and change `createdDateOp` to be `greater` since we need to match records with date past `createdDate`.
https://folio-org.atlassian.net/browse/UIINREACH-236
> UIINREACH-236: Owning site paged too long report not honoring "minimum days paged" value

- CHANGELOG.md
- src/settings/components/FolioToInnReachLocations/FolioToInnReachLocationsForm/components/LibraryTabularLists/LibraryTabularLists.js
- src/settings/components/FolioToInnReachLocations/FolioToInnReachLocationsForm/components/LibraryTabularLists/LibraryTabularLists.test.js
Fix a bug in `LibraryTabularLists` component that causes page crashes when `pickedLocationsByAgencyCode` is empty, while maintaining proper location uniqueness constraints across agencies.
- **Bug Fix**: Added null safety check for `pickedLocationsByAgencyCode[localAgencyCode]` with fallback to empty array
- **Logic Enhancement**: Added conditional check for array length and valid index before attempting to splice operation
[UIINREACH-258](https://folio-org.atlassian.net/browse/UIINREACH-258)
> UIINREACH-258: Fix `LibraryTabularLists` crash when `pickedLocationsByAgencyCode` is empty.
